const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const tools=[['新增','＋','開始創作'],['調整','⌗','尺寸與構圖'],['文字','T','文字排版'],['消除圖','⌁','移除不需要的內容'],['摳圖','♧','主體與背景'],['變清晰','✧','細節與解析度'],['調色','◐','色彩與氛圍'],['影片摳圖','▷','動態影像']];
const canvas=$('#canvas'),ctx=canvas.getContext('2d'),overlay=$('#overlay'),oc=overlay.getContext('2d');
const make=(w,h)=>{let c=document.createElement('canvas');c.width=w;c.height=h;return c},copy=c=>{let d=make(c.width,c.height);d.getContext('2d').drawImage(c,0,0);return d};
let source=null,original=null,before=null,tool=0,history=[],future=[],zoom=1,pan={x:0,y:0},space=false,drag=null,selection=null,brush=false,brushSize=40,showOriginal=false,split=null,filename='作品',mode='photo',cancelled=false,busy=false,segmentation=null,maskBase=null,maskOriginal=null;
let adjustments={brightness:100,contrast:100,saturate:100,temperature:0,hue:0};
let videoURL=null,videoFile=null,videoResult=null;
function toast(t){$('#toast').textContent=t;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,4800)}
function modal(html){$('#dialogContent').innerHTML=html;$('#dialog').showModal()}
$('.close').onclick=()=>$('#dialog').close();$('#dialog').onclick=e=>{if(e.target===$('#dialog'))$('#dialog').close()};
function setBusy(v,text='準備處理…'){busy=v;$('#busy').hidden=!v;$('#progressText').textContent=text;$('#progress').removeAttribute('value');$('#cancel').textContent='取消處理';$('#cancel').disabled=false;document.querySelectorAll('header button,nav button,.history button,#settings button,#settings input,#settings select,#settings textarea').forEach(b=>{if(v){b.dataset.wasDisabled=b.disabled?'1':'0';b.disabled=true}else{b.disabled=b.dataset.wasDisabled==='1';delete b.dataset.wasDisabled}});if(!v)updateHistory()}
$('#cancel').onclick=()=>{cancelled=true;$('#cancel').textContent='正在取消…';$('#cancel').disabled=true;$('#progressText').textContent='等待目前運算結束，原畫面會保留'};
function checkpoint(){history.push({image:copy(source),adjustments:{...adjustments}});if(history.length>12)history.shift();future=[];updateHistory()}
function updateHistory(){$('#undo').disabled=!history.length||busy;$('#redo').disabled=!future.length||busy}
function changed(next,{compare=false}={}){checkpoint();before=compare?copy(source):null;source=next;adjustments={brightness:100,contrast:100,saturate:100,temperature:0,hue:0};split=compare?.5:null;selection=null;maskBase=null;maskOriginal=null;draw();fit();renderPanel()}
function filter(){return `brightness(${adjustments.brightness}%) contrast(${adjustments.contrast}%) saturate(${adjustments.saturate}%) sepia(${Math.max(0,adjustments.temperature)/200}) hue-rotate(${adjustments.hue+Math.min(0,adjustments.temperature)/3}deg)`}
function rendered(){const c=copy(source),x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);x.filter=filter();x.drawImage(source,0,0);return c}
function draw(){if(!source)return;canvas.width=source.width;canvas.height=source.height;overlay.width=source.width;overlay.height=source.height;ctx.filter=showOriginal?'none':filter();ctx.drawImage(showOriginal?original:source,0,0,canvas.width,canvas.height);ctx.filter='none';if(before&&split!==null&&!showOriginal){ctx.save();ctx.beginPath();ctx.rect(0,0,canvas.width*split,canvas.height);ctx.clip();ctx.drawImage(before,0,0,canvas.width,canvas.height);ctx.restore()}
$('#empty').hidden=true;$('#artboard').hidden=mode!=='photo';$('#artboard').style.width=canvas.width+'px';$('#artboard').style.height=canvas.height+'px';$('#dimensions').textContent=`${canvas.width.toLocaleString()} × ${canvas.height.toLocaleString()} px`;$('#split').hidden=split===null;$('#compareLabels').hidden=split===null;$('#split').style.left=canvas.width*(split||0)+'px';if(selection){oc.strokeStyle='#d9ef89';oc.lineWidth=2/zoom;oc.setLineDash([6/zoom,4/zoom]);oc.fillStyle='#d9ef8925';oc.fillRect(selection.x,selection.y,selection.w,selection.h);oc.strokeRect(selection.x,selection.y,selection.w,selection.h)}transform()}
function transform(){$('#artboard').style.transform=`translate(${pan.x}px,${pan.y}px) scale(${zoom})`;$('#zoomLabel').textContent=Math.round(zoom*100)+'%'}
function fit(){if(!source)return;const r=$('#stage').getBoundingClientRect();zoom=Math.min((r.width-80)/source.width,(r.height-80)/source.height,1);zoom=Math.max(.01,zoom);pan={x:(r.width-source.width*zoom)/2,y:(r.height-source.height*zoom)/2};transform()}
function zoomAt(f,x,y){const z=Math.max(.01,Math.min(12,zoom*f));pan.x=x-(x-pan.x)*z/zoom;pan.y=y-(y-pan.y)*z/zoom;zoom=z;transform()}
$('#stage').addEventListener('wheel',e=>{if(!source||mode!=='photo')return;e.preventDefault();const r=$('#stage').getBoundingClientRect();zoomAt(Math.exp(-e.deltaY*.001),e.clientX-r.left,e.clientY-r.top)},{passive:false});
$('#zoomIn').onclick=()=>{const r=$('#stage').getBoundingClientRect();zoomAt(1.2,r.width/2,r.height/2)};$('#zoomOut').onclick=()=>{const r=$('#stage').getBoundingClientRect();zoomAt(1/1.2,r.width/2,r.height/2)};$('#fit').onclick=fit;$('#zoomLabel').onclick=()=>{if(!source)return;zoom=1;const r=$('#stage').getBoundingClientRect();pan={x:(r.width-source.width)/2,y:(r.height-source.height)/2};transform()};
const point=e=>{const r=canvas.getBoundingClientRect();return{x:Math.max(0,Math.min(canvas.width,(e.clientX-r.left)/zoom)),y:Math.max(0,Math.min(canvas.height,(e.clientY-r.top)/zoom))}};
$('#stage').onpointerdown=e=>{if(busy||mode!=='photo'||!source)return;if(space||e.button===1){drag={kind:'pan',x:e.clientX,y:e.clientY,px:pan.x,py:pan.y};$('#stage').setPointerCapture(e.pointerId);return}if(e.target.closest('#split')){drag={kind:'split'};$('#stage').setPointerCapture(e.pointerId);return}if(e.target!==overlay)return;const p=point(e);if(tool===1||tool===3){drag={kind:brush&&tool===3?'erase':'rect',p};selection={x:p.x,y:p.y,w:0,h:0};if(drag.kind==='erase')paintMask(p);$('#stage').setPointerCapture(e.pointerId)}else if(tool===4&&maskBase){checkpoint();drag={kind:'repair',last:p};repair(p);$('#stage').setPointerCapture(e.pointerId)}};
$('#stage').onpointermove=e=>{if(!drag)return;if(drag.kind==='pan'){pan={x:drag.px+e.clientX-drag.x,y:drag.py+e.clientY-drag.y};transform()}else if(drag.kind==='split'){split=point(e).x/source.width;draw()}else if(drag.kind==='rect'){const p=point(e);selection={x:Math.min(drag.p.x,p.x),y:Math.min(drag.p.y,p.y),w:Math.abs(p.x-drag.p.x),h:Math.abs(p.y-drag.p.y)};draw()}else if(drag.kind==='erase')paintMask(point(e));else if(drag.kind==='repair')repair(point(e))};
$('#stage').onpointerup=()=>{let kind=drag?.kind;drag=null;if(kind==='erase')toast('塗抹遮罩已建立。MI-GAN 尚未接入，未修改圖片。')};
function paintMask(p){oc.fillStyle='#d9ef8990';oc.beginPath();oc.arc(p.x,p.y,brushSize/2,0,Math.PI*2);oc.fill()}
function repair(p){const x=source.getContext('2d');x.save();x.beginPath();x.arc(p.x,p.y,brushSize/2,0,Math.PI*2);x.clip();if($('#repairMode')?.value==='restore')x.drawImage(maskOriginal,0,0);else x.clearRect(p.x-brushSize/2,p.y-brushSize/2,brushSize,brushSize);x.restore();draw()}
window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();space=true;$('#stage').style.cursor='grab'}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();(e.shiftKey?$('#redo'):$('#undo')).click()}});window.addEventListener('keyup',e=>{if(e.code==='Space'){space=false;$('#stage').style.cursor='';drag=null}});window.addEventListener('blur',()=>{space=false;showOriginal=false;draw()});
$('#undo').onclick=()=>{if(!history.length)return;future.push({image:copy(source),adjustments:{...adjustments}});const s=history.pop();source=s.image;adjustments=s.adjustments;before=null;split=null;maskBase=null;selection=null;draw();fit();renderPanel();updateHistory()};$('#redo').onclick=()=>{if(!future.length)return;history.push({image:copy(source),adjustments:{...adjustments}});const s=future.pop();source=s.image;adjustments=s.adjustments;before=null;split=null;draw();fit();renderPanel();updateHistory()};$('#reset').onclick=()=>{if(!original||busy)return;changed(copy(original));toast('已重置為原始圖片')};$('#compare').onpointerdown=e=>{if(!source)return;showOriginal=true;draw();e.currentTarget.setPointerCapture(e.pointerId)};$('#compare').onpointerup=$('#compare').onpointercancel=()=>{showOriginal=false;draw()};
async function importImage(file){if(busy)return;if(!file?.type.startsWith('image/'))return toast('請選擇 PNG、JPG 或 WebP 圖片');try{let img=await createImageBitmap(file);if(img.width*img.height>40000000){img.close();return toast('第一版支援 4,000 萬像素以內的圖片，請先縮小圖片')}source=make(img.width,img.height);source.getContext('2d').drawImage(img,0,0);img.close();original=copy(source);history=[];future=[];before=null;split=null;maskBase=null;selection=null;adjustments={brightness:100,contrast:100,saturate:100,temperature:0,hue:0};filename=file.name.replace(/\.[^.]+$/,'');$('#filename').textContent=file.name;setMode('photo');draw();fit();updateHistory();toast('圖片已加入，全程留在瀏覽器內')}catch(e){toast('無法讀取這張圖片，請改用 PNG 或 JPG')}}
$('#file').onchange=e=>{importImage(e.target.files[0]);e.target.value=''};$('#emptyImport').onclick=()=>$('#file').click();$('#stage').ondragover=e=>{e.preventDefault();$('#stage').classList.add('dragover')};$('#stage').ondragleave=()=>$('#stage').classList.remove('dragover');$('#stage').ondrop=e=>{e.preventDefault();$('#stage').classList.remove('dragover');const f=e.dataTransfer.files[0];if(f?.type.startsWith('video/'))importVideo(f);else importImage(f)};window.addEventListener('paste',e=>{if(busy||/INPUT|TEXTAREA/.test(e.target.tagName))return;const f=[...e.clipboardData.items].find(i=>i.type.startsWith('image/'))?.getAsFile();if(f)importImage(f)});
function requireImage(){if(!source){toast('請先加入一張圖片');return false}return true}
function bind(id,fn){const el=$('#'+id);if(el)el.onclick=fn}
function range(id,label,value,min,max){return `<div class="range-row"><span>${label}</span><output id="${id}Value">${value}</output></div><input id="${id}" type="range" min="${min}" max="${max}" value="${value}" aria-label="${label}">`}
function renderTools(){$('#tools').innerHTML=(mode==='photo'?tools: [['新增','＋'],['影片去水印','⌁'],['影片去背','♧'],['影片放大','✧']]).map((t,i)=>`<button class="${tool===i?'active':''}" data-tool="${i}"><span class="icon">${t[1]}</span>${t[0]}</button>`).join('');$$('[data-tool]').forEach(b=>b.onclick=()=>{tool=+b.dataset.tool;selection=null;brush=false;draw();renderTools();renderPanel()})}
function renderPanel(){const s=$('#settings');$('#toolTitle').textContent=mode==='photo'?tools[tool][0]:['新增影片','影片去水印','影片去背','影片放大'][tool];$('#toolEyebrow').textContent=mode==='photo'?tools[tool][2]:'瀏覽器影片工作台';$('#hint').textContent=mode==='video'?'MP4 / WebM · 原始聲音保留':source?'滾輪縮放 · 空白鍵拖曳 · Ctrl+Z 復原':'拖曳或貼上圖片開始編輯';
if(mode==='video'){renderVideoPanel();return}
if(tool===0){s.innerHTML=`<div class="dropzone"><div class="big">▧</div><button id="import" class="primary">＋ 選擇圖片</button><p>拖曳檔案到畫布<br>或使用 Ctrl / ⌘ + V 貼上</p><span class="pill">PNG · JPG · WebP</span></div><div class="section"><h3>從空白畫布開始</h3><div class="grid"><button id="blankSquare">正方形</button><button id="blankLandscape">橫式畫布</button></div><p class="note">加入文字，或製作簡單的色彩版面。</p></div><div class="section"><h3>你的檔案，只屬於你</h3><p class="note">所有編輯都在此分頁完成。關閉分頁前，記得匯出作品。</p></div>`;bind('import',()=>$('#file').click());bind('blankSquare',()=>blank(1080,1080));bind('blankLandscape',()=>blank(1920,1080))}
if(tool===1){s.innerHTML=`<h3>裁剪比例</h3><div class="grid three">${[['自由',0],['1:1',1],['4:3',4/3],['3:2',1.5],['16:9',16/9],['9:16',9/16]].map(([t,r])=>`<button data-ratio="${r}">${t}</button>`).join('')}</div><p class="note">在畫布拖曳框選範圍，或選擇置中比例。</p><button id="crop" class="primary full">套用裁剪</button><div class="section"><h3>常用尺寸</h3><select id="sizePreset"><option value="1080,1080">社群貼文 · 1080 × 1080</option><option value="1080,1920">限時動態 · 1080 × 1920</option><option value="1920,1080">Full HD · 1920 × 1080</option><option value="1200,630">分享封面 · 1200 × 630</option></select><label>寬度 × 高度（像素）</label><div class="grid"><input id="width" type="number" min="1" max="8192" value="${source?.width||1080}" aria-label="寬度"><input id="height" type="number" min="1" max="8192" value="${source?.height||1080}" aria-label="高度"></div><label class="toggle"><input id="lockAspect" type="checkbox" checked> 保持原始比例</label><button class="full" id="resize">調整尺寸</button></div><div class="section"><h3>旋轉與翻轉</h3><div class="grid"><button id="rotateL">↶ 左轉 90°</button><button id="rotateR">↷ 右轉 90°</button><button id="flipH">↔ 水平翻轉</button><button id="flipV">↕ 垂直翻轉</button></div><h3>形狀蒙版</h3><div class="grid"><button id="circle">圓形</button><button id="rounded">圓角矩形</button></div></div>`;$$('[data-ratio]').forEach(b=>b.onclick=()=>{if(!requireImage())return;let r=+b.dataset.ratio;if(!r){selection=null;draw();return}let w=source.width,h=w/r;if(h>source.height){h=source.height;w=h*r}selection={x:(source.width-w)/2,y:(source.height-h)/2,w,h};draw()});bind('crop',()=>{if(!requireImage())return;if(!selection||selection.w<1||selection.h<1)return toast('先在畫布框選裁剪範圍');const {x,y,w,h}=selection;let c=make(Math.round(w),Math.round(h));c.getContext('2d').drawImage(rendered(),x,y,w,h,0,0,c.width,c.height);changed(c)});$('#sizePreset').onchange=e=>{let [w,h]=e.target.value.split(',');$('#width').value=w;$('#height').value=h;$('#lockAspect').checked=false};$('#width').oninput=()=>{if(source&&$('#lockAspect').checked)$('#height').value=Math.round(+$('#width').value*source.height/source.width)};$('#height').oninput=()=>{if(source&&$('#lockAspect').checked)$('#width').value=Math.round(+$('#height').value*source.width/source.height)};bind('resize',()=>resize(+$('#width').value,+$('#height').value));bind('rotateL',()=>rotate(-1));bind('rotateR',()=>rotate(1));bind('flipH',()=>flip(true));bind('flipV',()=>flip(false));bind('circle',()=>shape('circle'));bind('rounded',()=>shape('rounded'))}
if(tool===2){s.innerHTML=`<h3>文字樣式</h3><div class="grid"><button data-style="title">標題</button><button data-style="subtitle">副標題</button><button data-style="body">正文</button><button data-style="outline">花字 · 描邊</button></div><label for="textContent">文字內容</label><textarea id="textContent" rows="3" placeholder="輸入你的文字">讓靈感成為作品</textarea><label>字體</label><select id="font"><option value="sans-serif">黑體</option><option value="serif">明體</option><option value="monospace">等寬字體</option></select>${range('fontSize','文字大小',Math.max(16,Math.round((source?.width||1080)*.06)),12,300)}<label>文字顏色</label><input id="textColor" type="color" value="#ffffff"><label>文字位置</label><select id="textPosition"><option value="center">畫面中央</option><option value="top">畫面上方</option><option value="bottom">畫面下方</option></select><button id="addText" class="primary full">加入文字</button><p class="note">文字會套用到圖片，可使用復原移除。</p>`;let style='title';$$('[data-style]').forEach(b=>b.onclick=()=>{style=b.dataset.style;$$('[data-style]').forEach(t=>t.classList.toggle('active',t===b));$('#fontSize').value=Math.round((source?.width||1080)*({title:.08,subtitle:.045,body:.025,outline:.08}[style]));$('#fontSizeValue').textContent=$('#fontSize').value});$('#fontSize').oninput=e=>$('#fontSizeValue').textContent=e.target.value;bind('addText',()=>{if(!requireImage())return;let text=$('#textContent').value.trim();if(!text)return toast('請輸入文字');let c=rendered(),x=c.getContext('2d'),size=+$('#fontSize').value,lines=text.split('\n');x.font=`${style==='title'||style==='outline'?'bold':''} ${size}px ${$('#font').value}`;x.textAlign='center';x.textBaseline='middle';x.fillStyle=$('#textColor').value;let y=({top:.15,center:.5,bottom:.85}[$('#textPosition').value])*c.height;lines.forEach((t,i)=>{let yy=y+(i-(lines.length-1)/2)*size*1.3;if(style==='outline'){x.lineWidth=Math.max(2,size*.06);x.strokeStyle='#1b1e25';x.strokeText(t,c.width/2,yy,c.width*.92)}x.fillText(t,c.width/2,yy,c.width*.92)});changed(c)})}
if(tool===3){s.innerHTML=`<h3>消除方式</h3><div class="grid"><button id="rectMode" class="active">框選水印</button><button id="brushMode">塗抹消除</button></div>${range('brushSize','筆刷大小',brushSize,5,200)}<p class="note">在畫布框住水印，或塗抹不需要的部分。</p><button id="erase" class="full" disabled>MI-GAN · 尚未接入</button><p class="note">第一版可建立消除選區。AI 填補模型尚未完成瀏覽器轉換，目前不會修改選區中的像素。</p><button id="clearSelection" class="full">清除選區</button>`;bind('rectMode',()=>{brush=false;$('#rectMode').classList.add('active');$('#brushMode').classList.remove('active')});bind('brushMode',()=>{brush=true;$('#rectMode').classList.remove('active');$('#brushMode').classList.add('active')});$('#brushSize').oninput=e=>{brushSize=+e.target.value;$('#brushSizeValue').textContent=brushSize};bind('clearSelection',()=>{selection=null;draw()})}
if(tool===4){s.innerHTML=`<h3>AI 一鍵摳圖 <span class="pill">本機 GPU</span></h3><p class="note">此版使用 RMBG-1.4。U²-Net 指定模型尚未接入。首次會下載模型，照片不會傳送。</p><button id="removeBG" class="primary full">✧ 移除背景</button>${range('retain','主體保留',50,0,100)}<div class="section"><h3>筆刷修補</h3><select id="repairMode"><option value="restore">保留 · 還原主體</option><option value="erase">移除 · 擦去背景</option></select>${range('repairSize','筆刷大小',brushSize,5,200)}<p class="note">摳圖後，在畫布塗抹進行修補。</p></div><div class="section"><h3>換背景</h3><input id="bgColor" type="color" value="#ffffff"><button id="setBG" class="full">套用背景顏色</button><button id="transparentExport" class="primary full">下載透明 PNG</button></div>`;bind('removeBG',removeBackground);$('#retain').oninput=e=>{$('#retainValue').textContent=e.target.value};$('#retain').onchange=e=>{if(!maskBase)return toast('先完成 AI 摳圖');checkpoint();source=copy(maskBase);let x=source.getContext('2d'),d=x.getImageData(0,0,source.width,source.height),v=(+e.target.value-50)*2;for(let i=3;i<d.data.length;i+=4)d.data[i]=Math.max(0,Math.min(255,d.data[i]+v));x.putImageData(d,0,0);draw()};$('#repairSize').oninput=e=>{brushSize=+e.target.value;$('#repairSizeValue').textContent=brushSize};bind('setBG',()=>{if(!requireImage())return;let c=make(source.width,source.height),x=c.getContext('2d');x.fillStyle=$('#bgColor').value;x.fillRect(0,0,c.width,c.height);x.drawImage(rendered(),0,0);changed(c)});bind('transparentExport',()=>downloadImage('image/png'))}
if(tool===5){s.innerHTML=`<h3>AI 放大倍率</h3><div class="grid"><button disabled>2 倍</button><button disabled>4 倍</button></div><h3>模型</h3><select disabled><option>Real-ESRGAN · 快速</option><option>Upscayl · 標準</option><option>Upscayl · 數位藝術</option></select><button class="full" disabled>AI 模型尚未接入</button><p class="note">以上三種 AI 模型尚未完成 WebGPU 移植。你可以先測試一般高品質縮放，結果不包含 AI 生成細節。</p><div class="section"><h3>一般縮放</h3><div class="grid"><button id="scale2">一般 2 倍</button><button id="scale4">一般 4 倍</button></div><p class="note">使用瀏覽器重採樣，完成後可拖曳前後對比線。</p></div>`;bind('scale2',()=>{if(requireImage())resize(source.width*2,source.height*2,true)});bind('scale4',()=>{if(requireImage())resize(source.width*4,source.height*4,true)})}
if(tool===6){s.innerHTML=`<h3>色彩預設</h3><div class="grid">${['原色','暖陽','冷調','黑白'].map((t,i)=>`<button class="preset" data-preset="${i}">${t}</button>`).join('')}</div><div class="section"><h3>細部調整</h3>${range('brightness','亮度',adjustments.brightness,0,200)}${range('contrast','對比',adjustments.contrast,0,200)}${range('saturate','飽和度',adjustments.saturate,0,200)}${range('temperature','色溫',adjustments.temperature,-100,100)}${range('hue','色相 / 一鍵換色',adjustments.hue,-180,180)}</div><button id="commitColor" class="primary full">套用調色</button>`;$$('[data-preset]').forEach(b=>b.onclick=()=>{if(!requireImage())return;checkpoint();adjustments=[{brightness:100,contrast:100,saturate:100,temperature:0,hue:0},{brightness:108,contrast:105,saturate:110,temperature:45,hue:0},{brightness:100,contrast:112,saturate:85,temperature:-40,hue:0},{brightness:100,contrast:115,saturate:0,temperature:0,hue:0}][+b.dataset.preset];draw();renderPanel()});Object.keys(adjustments).forEach(k=>{let marked=false;$('#'+k).oninput=e=>{if(!source)return;if(!marked){checkpoint();marked=true}adjustments[k]=+e.target.value;$('#'+k+'Value').textContent=e.target.value;draw()};$('#'+k).onchange=()=>marked=false});bind('commitColor',()=>{if(requireImage())changed(rendered())})}
if(tool===7){s.innerHTML=`<h3>逐格影片去背</h3><p class="note">切換到影片工具，加入 MP4 或 WebM 並拖動時間軸。</p><button id="goVideo" class="primary full">開啟影片工具</button><div class="section"><h3>開發狀態</h3><p class="note">逐格 AI 辨識、邊緣穩定和透明 WebM 編碼尚未接入。第一版先提供影片預覽及保留聲音的一般放大。</p></div>`;bind('goVideo',()=>{setMode('video');tool=2;renderTools();renderPanel()})}}
function blank(w,h){let c=make(w,h);c.getContext('2d').fillStyle='#eaece4';c.getContext('2d').fillRect(0,0,w,h);source=c;original=copy(c);history=[];future=[];filename='空白畫布';$('#filename').textContent=filename;adjustments={brightness:100,contrast:100,saturate:100,temperature:0,hue:0};before=null;split=null;draw();fit();updateHistory()}
function resize(w,h,compare=false){if(!requireImage())return;if(!Number.isInteger(w)||!Number.isInteger(h)||w<1||h<1||w>8192||h>8192||w*h>40000000)return toast('尺寸需介於 1–8192，總像素不超過 4,000 萬');const c=make(w,h),x=c.getContext('2d');x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';x.drawImage(rendered(),0,0,w,h);changed(c,{compare})}
function rotate(dir){if(!requireImage())return;let c=make(source.height,source.width),x=c.getContext('2d');x.translate(c.width/2,c.height/2);x.rotate(dir*Math.PI/2);x.drawImage(rendered(),-source.width/2,-source.height/2);changed(c)}
function flip(horizontal){if(!requireImage())return;let c=make(source.width,source.height),x=c.getContext('2d');x.translate(horizontal?c.width:0,horizontal?0:c.height);x.scale(horizontal?-1:1,horizontal?1:-1);x.drawImage(rendered(),0,0);changed(c)}
function shape(type){if(!requireImage())return;let c=make(source.width,source.height),x=c.getContext('2d');x.beginPath();if(type==='circle')x.ellipse(c.width/2,c.height/2,c.width/2,c.height/2,0,0,Math.PI*2);else x.roundRect(0,0,c.width,c.height,Math.min(c.width,c.height)*.1);x.clip();x.drawImage(rendered(),0,0);changed(c)}
async function removeBackground(){if(!requireImage()||busy)return;if(!navigator.gpu)return toast('這個瀏覽器不支援 WebGPU，請使用新版 Chrome 或 Edge');cancelled=false;setBusy(true,'載入 AI 模型…首次下載可能需要數分鐘');try{const {AutoModel,AutoProcessor,RawImage}=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.7.2');if(cancelled)return;if(!segmentation){let processor=await AutoProcessor.from_pretrained('onnx-community/RMBG-1.4');let model=await AutoModel.from_pretrained('onnx-community/RMBG-1.4',{device:'webgpu',dtype:'fp32',progress_callback:p=>{if(p.status==='progress'){$('#progressText').textContent=`下載模型 ${Math.round(p.progress||0)}%`;$('#progress').value=p.progress||0}}});segmentation={processor,model,RawImage}}if(cancelled)return;$('#progressText').textContent='辨識主體與邊緣…';$('#progress').removeAttribute('value');const input=await segmentation.RawImage.fromURL(rendered().toDataURL()),processed=await segmentation.processor(input);const output=await segmentation.model({input:processed.pixel_values});if(cancelled)return;const tensor=output.output??Object.values(output)[0];const mask=await segmentation.RawImage.fromTensor(tensor.squeeze().mul(255).clamp(0,255).to('uint8')).resize(source.width,source.height);const c=rendered(),x=c.getContext('2d'),d=x.getImageData(0,0,c.width,c.height);for(let i=0;i<c.width*c.height;i++)d.data[i*4+3]=Math.round(d.data[i*4+3]*mask.data[i*mask.channels]/255);x.putImageData(d,0,0);const raw=rendered();changed(c);maskBase=copy(c);maskOriginal=raw;toast('背景已移除，可用筆刷修補或下載透明 PNG')}catch(e){console.error(e);if(!cancelled)toast('AI 模型載入或運算失敗。請檢查網路與 WebGPU 支援；原圖已保留。')}finally{if(cancelled)toast('已取消，畫面維持原樣');setBusy(false)}}
async function downloadImage(type,quality=.92){if(!requireImage())return;let c=rendered();if(type==='image/jpeg'){let white=make(c.width,c.height),x=white.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);x.drawImage(c,0,0);c=white}const blob=await new Promise(r=>c.toBlob(r,type,quality));if(!blob)return toast('匯出失敗，請縮小圖片後重試');saveBlob(blob,filename+'.'+({'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[blob.type]||'png'));toast('作品已匯出')}
function saveBlob(blob,name){let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),10000)}
$('#exportTop').onclick=()=>{if(mode==='video'){if(videoResult)saveBlob(videoResult,'光室影片.webm');else if(videoFile)saveBlob(videoFile,videoFile.name);else toast('請先加入影片');return}if(!requireImage())return;modal(`<h2>匯出作品</h2><p class="muted">${source.width} × ${source.height} 像素 · 保存在你的裝置</p><label>檔案格式</label><select id="exportFormat"><option value="image/png">PNG · 支援透明背景</option><option value="image/jpeg">JPG · 透明區域填白</option><option value="image/webp">WebP · 體積較小</option></select>${range('quality','JPG / WebP 品質',92,10,100)}<button id="download" class="primary full">下載圖片</button>`);$('#quality').oninput=e=>$('#qualityValue').textContent=e.target.value;$('#download').onclick=()=>{downloadImage($('#exportFormat').value,+$('#quality').value/100);$('#dialog').close()}};
function setMode(m){mode=m;tool=0;$('#photoTab').classList.toggle('active',m==='photo');$('#videoTab').classList.toggle('active',m==='video');$('#artboard').hidden=m!=='photo'||!source;$('#videoBox').hidden=m!=='video'||!videoFile;$('#timeline').hidden=m!=='video'||!videoFile;$('#empty').hidden=m==='photo'?!!source:!!videoFile;$('#empty h2').textContent=m==='photo'?'好作品，從一張圖片開始':'把影片帶進工作台';$('#empty p').textContent=m==='photo'?'把圖片拖曳到這裡，或直接貼上':'拖曳 MP4 或 WebM，預覽你的影片';$('#emptyImport').textContent=m==='photo'?'選擇圖片':'選擇影片';$('#empty small').textContent=m==='photo'?'PNG、JPG、WebP · 全程在瀏覽器處理':'MP4、WebM · 保留聲音';$('#emptyImport').onclick=()=>$(m==='photo'?'#file':'#videoFile').click();if(m==='photo'){$('#video').pause();$('#filename').textContent=source?filename:'未命名作品';if(source)draw()}else{$('#filename').textContent=videoFile?.name||'未命名影片';$('#dimensions').textContent=videoFile?`${$('#video').videoWidth} × ${$('#video').videoHeight} px`:'尚未加入影片'}renderTools();renderPanel()}
$('#photoTab').onclick=()=>setMode('photo');$('#videoTab').onclick=()=>setMode('video');
function renderVideoPanel(){let s=$('#settings');if(tool===0){s.innerHTML=`<div class="dropzone"><div class="big">▷</div><button id="importVideo" class="primary">選擇影片</button><p>支援 MP4 和 WebM<br>拖曳到畫布也可以</p></div><h3>第一版影片流程</h3><p class="note">本機播放、時間軸預覽，以及保留聲音的一般 2 倍 / 4 倍放大。AI 逐格處理尚未接入。</p>`;bind('importVideo',()=>$('#videoFile').click())}if(tool===1){s.innerHTML=`<h3>固定位置水印</h3><p class="note">影片 AI 去水印尚未接入。後續將加入多選區、逐格填補及時間軸檢查。</p><button class="full" disabled>AI 逐格填補 · 尚未接入</button><p class="note">目前可在右側播放影片並拖動時間軸，匯出按鈕會下載原始影片。</p>`}if(tool===2){s.innerHTML=`<h3>背景設定</h3><select disabled><option>透明 · WebM</option><option>綠幕</option><option>白色</option><option>原畫面模糊</option><option>自訂顏色</option></select><label class="toggle"><input type="checkbox" checked disabled> 減少邊緣閃爍</label><button class="full" disabled>逐格去背 · 尚未接入</button><p class="note">影片逐格 AI、時間一致性與透明編碼尚未完成，這些設定目前不會改變影片。</p>`}if(tool===3){s.innerHTML=`<h3>一般影片放大</h3><div class="grid"><button id="video2">2 倍</button><button id="video4">4 倍</button></div><p class="note">上限 3840 × 2160，保持比例。使用瀏覽器重採樣，不是 AI 超解析度。</p><label>匯出格式</label><select disabled><option>WebM · 保留聲音</option></select><p class="note">支援 MP4 / WebM 輸入，輸出 WebM。影片按正常速度播放並錄製，請保持分頁在前景。MP4 輸出尚未接入。</p><div class="section"><h3>AI 放大</h3><button class="full" disabled>AI 模型尚未接入</button></div>`;bind('video2',()=>exportVideo(2));bind('video4',()=>exportVideo(4))}}
async function importVideo(f){if(busy)return;if(!['video/mp4','video/webm'].includes(f?.type))return toast('請選擇 MP4 或 WebM 影片');if(videoURL)URL.revokeObjectURL(videoURL);videoURL=URL.createObjectURL(f);const v=$('#video');v.src=videoURL;v.onloadedmetadata=()=>{videoFile=f;videoResult=null;$('#seek').max=v.duration;setMode('video');toast('影片已加入，可播放或拖動時間軸')};v.onerror=()=>toast('瀏覽器無法解碼這支影片，請改用 H.264 MP4 或 VP9 WebM')}
$('#videoFile').onchange=e=>{importVideo(e.target.files[0]);e.target.value=''};$('#play').onclick=()=>{let v=$('#video');v.paused?v.play():v.pause()};$('#seek').oninput=e=>$('#video').currentTime=+e.target.value;$('#video').ontimeupdate=()=>{let v=$('#video');$('#seek').value=v.currentTime;$('#time').textContent=Math.floor(v.currentTime/60)+':'+String(Math.floor(v.currentTime%60)).padStart(2,'0')};
async function exportVideo(scale){if(!videoFile)return toast('請先加入影片');if(busy)return;const v=$('#video');if(!v.captureStream||!window.MediaRecorder)return toast('此瀏覽器不支援影片錄製，請使用新版 Chrome 或 Edge');const mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus'].find(x=>MediaRecorder.isTypeSupported(x));if(!mime)return toast('瀏覽器不支援 WebM 匯出');let factor=Math.min(scale,3840/v.videoWidth,2160/v.videoHeight),w=Math.max(2,Math.floor(v.videoWidth*factor/2)*2),h=Math.max(2,Math.floor(v.videoHeight*factor/2)*2);const out=make(w,h),x=out.getContext('2d'),old=v.currentTime,oldMuted=v.muted;let rec,stream,raf;cancelled=false;setBusy(true,'準備匯出 WebM…');try{v.pause();v.currentTime=0;await new Promise(resolve=>{if(v.readyState>=2&&v.currentTime===0)resolve();else v.addEventListener('seeked',resolve,{once:true})});await v.play();const input=v.captureStream();stream=out.captureStream(30);input.getAudioTracks().forEach(t=>stream.addTrack(t));let chunks=[];rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:Math.min(30000000,w*h*5)});const complete=new Promise((resolve,reject)=>{rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};rec.onstop=()=>resolve(new Blob(chunks,{type:'video/webm'}));rec.onerror=()=>reject(new Error('編碼失敗'))});rec.start(1000);let stopped=false;const tick=()=>{x.imageSmoothingQuality='high';x.drawImage(v,0,0,w,h);$('#progress').value=Math.min(100,v.currentTime/v.duration*100);$('#progressText').textContent=`匯出 ${w} × ${h} · ${Math.round(v.currentTime/v.duration*100)}%`;if(cancelled||v.ended){if(!stopped){stopped=true;rec.stop()}return}raf=requestAnimationFrame(tick)};tick();const blob=await complete;if(!cancelled){videoResult=blob;saveBlob(blob,videoFile.name.replace(/\.[^.]+$/,'')+'-影片放大.webm');toast('影片已匯出為 WebM')}else toast('已取消，原始影片保持不變')}catch(e){console.error(e);toast('影片匯出失敗，原始影片已保留')}finally{cancelAnimationFrame(raf);if(rec?.state==='recording')rec.stop();stream?.getTracks().forEach(t=>t.stop());v.pause();v.currentTime=old;v.muted=oldMuted;setBusy(false)}}
$('#capabilities').onclick=()=>modal(`<h2>第一版功能狀態</h2><ul class="status-list"><li>可用：圖片匯入、裁剪、尺寸、形狀、旋轉翻轉、文字、調色、復原重做、PNG / JPG / WebP 匯出。</li><li>可用：游標中心縮放、空白鍵平移、按住原圖對比、一般放大前後對比。</li><li>試用：RMBG-1.4 WebGPU 圖片摳圖，需要 Chrome / Edge、可用顯示卡與模型下載。U²-Net 尚未接入。</li><li>可用：MP4 / WebM 本機預覽、時間軸、一般影片放大與 WebM 錄製，從原片串流保留音軌。</li><li>待完成：MI-GAN 消除、指定三種 AI 放大模型、影片 AI 去水印、影片 AI 去背、透明 WebM 與 MP4 編碼。</li></ul><p class="muted">AI 程式庫與模型會從 CDN / Hugging Face 下載。沒有照片或影片上傳 API。</p>`);
window.addEventListener('resize',()=>{if(!busy)fit()});renderTools();renderPanel();updateHistory();
